name: commit-stage-monolith

on:
  push:
    branches: [ "main" ]
    paths:
        - 'monolith/**'
        - '.github/workflows/commit-stage-monolith.yml'
  pull_request:
    branches: [ "main" ]
    paths:
        - 'monolith/**'
        - '.github/workflows/commit-stage-monolith.yml'
  workflow_dispatch:

concurrency:
  group: commit-stage-monolith-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image-digest-url: ${{ steps.push.outputs.image-digest-url }}

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Runtime
      uses: ./.github/actions/setup-dotnet
      with:
        dotnet-version: 8.0.x

    - name: Compile Code
      run: dotnet build Optivem.Greeter.Monolith.csproj
      working-directory: monolith

    # - name: Run Unit Tests
    # - name: Run Narrow Integration Tests
    # - name: Run Component Tests
    # - name: Run Contract Tests
    # - name: Run Linter
    # - name: Run Code Analysis

    - name: Build Docker Image
      id: build
      uses: optivem/actions/build-docker-image@v1
      with:
        working-directory: monolith
        image-name: monolith
        image-namespace: ${{ github.repository }}
        commit-sha: ${{ github.sha }}
        dockerfile: Dockerfile

    - name: Push Docker Image
      id: push
      uses: optivem/actions/push-docker-image@v1
      with:
        image-sha-tag: ${{ steps.build.outputs.image-sha-tag }}
        image-latest-url: ${{ steps.build.outputs.image-latest-url }}
        registry-username: ${{ github.actor }}
      env:
        REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  summary:
    needs: build
    runs-on: ubuntu-latest
    if: always()

    steps:
      
    - name: Commit Stage Summary
      uses: optivem/actions/summarize-commit-stage@v1
      with:
        stage-result: ${{ needs.build.result }}
        success-artifact-url: ${{ needs.build.outputs.image-digest-url }}
